language: ruby
rvm:
  - 2.6.6
install:
  - bundle install --jobs 3 --retry 3
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate RAILS_ENV=test
  - ruby -Itest test/models/exercicio_test.rb
  - ruby -Itest test/models/usuario_test.rb
  - ruby -Itest test/models/treino_test.rb
  - ruby -Itest test/models/anamnese_test.rb
  - bundle exec rails webpacker:compile
  - bundle exec cucumber
services:
  - postgresql
